Meal sharing - Week1
Saikiruthiga/meal-sharing pull request #1
Opened 2024-08-08 08:29 UTC by Saikiruthiga

added all routers
 - /future-meals
 - /past-meals
 - /all-meals
 - /first-meal
 - /last-meal

2024-08-08 12:17 UTC, magdazelena requested changes
added some comments that maybe we can work through together :)

2024-08-08 12:17 UTC, magdazelena commented on api/src/index.js
> +app.use("/last-meal", lastMealRouter);
I would encourage you to use this https://www.freecodecamp.org/news/rest-api-design-best-practices-build-a-rest-api/ tutorial to look into structuring practices in express api builiding :) in general `use` is rather limited to api groups instead of all the routes like here. Check the article, it has a lot of nice examples!

2024-08-08 12:17 UTC, magdazelena commented on api/src/routers/allMeals.js
> +    const meals = await knex.raw("select * from meal order by id asc");
can you explain why did you use the raw select here? :)

2024-08-08 12:17 UTC, magdazelena commented on api/src/routers/firstMeal.js
> +    const [meal] = await knex.raw("select * from meal order by id limit 1");
same here, why not use knex methods? :)

2024-08-08 12:17 UTC, magdazelena commented on api/src/routers/firstMeal.js
> +      : response.status(404).json({ Error: "No records found" });
I'll suggest not using ternary operator here for legibility :)
also, what type is `meal` object?

2024-08-09 02:50 UTC, Saikiruthiga commented on api/src/index.js
> +app.use("/last-meal", lastMealRouter);
Thank you for pointing out. I have updated the code

2024-08-09 02:55 UTC, Saikiruthiga commented on api/src/routers/allMeals.js
> +    const meals = await knex.raw("select * from meal order by id asc");
In the homework section, they recommend using 'knex.raw'. They mention "Our usage of Knex will get more advanced over the coming weeks but for now, we will focus on the simplified knex.raw function that can execute a raw SQL query." Could you please clarify whether i need to update this with advanced concepts from knex?

2024-08-09 03:22 UTC, Saikiruthiga commented on api/src/routers/firstMeal.js
> +      : response.status(404).json({ Error: "No records found" });
I just wanted to recall the concept, So I used the ternary operator.  I agree with your comment that it would be clear if i used a regular if statement instead. The type of meal is an object and this is a part of the array returned by the knex.raw statement. I am getting the output as follows {
    "id": 1,
    "title": "Smørrebrød",
    "description": "This dish is typically made with a slice of dense, dark rye bread (rugbrød) as the base. The bread is generously buttered and then topped with a variety of ingredients",
    "location": "Denmark",
    "when": "2024-08-19T05:00:35.000Z",
    "max_reservations": 20,
    "price": "50.00",
    "created_date": "2024-07-10T22:00:00.000Z"
}

2024-08-09 11:39 UTC, magdazelena commented on api/src/routers/allMeals.js
> +    const meals = await knex.raw("select * from meal order by id asc");
oh, then no! I'm sorry for confusing you, I didn't realise that part :) I'm sure it will come next then :)

2024-08-09 11:39 UTC, magdazelena commented on api/src/routers/firstMeal.js
> +      : response.status(404).json({ Error: "No records found" });
yes, thank you for clarifying! :)

2024-08-09 11:40 UTC, magdazelena approved these changes
good job <3

2024-08-10 15:58 UTC, merged